config/routes.rb
LamexJP::Application.routes.draw do
  resources :products

  get "home/index"

  root :to => 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/product_gallery.rb
class ProductGallery < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @product_gallery = ProductGallery.where({:product_id => @product::product_id})

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, :notice => 'Product was successfully created.' }
        format.json { render :json => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, :notice => 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to "Products", products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LamexJP</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :product_name %><br />
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :series_name %><br />
    <%= f.text_field :series_name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<script src="/assets/colorbox/jquery.colorbox-min.js"></script>
<script src="/assets/corner/jquery.corner.js"></script>
<script src="/assets/moving_boxes_content/js/jquery.easing.1.3.js"></script>
<script src="/assets/moving_boxes_content/js/jquery.jscrollpane.min.js"></script>
<script src="/assets/moving_boxes_content/js/jquery.mousewheel.js"></script>
<script src="/assets/moving_boxes_content/js/jquery.transform-0.9.3.min_.js"></script>
<script src="/assets/moving_boxes_content/js/init.js"></script>
<script src="/assets/js/jquery.corner.js"></script>
<link rel="stylesheet" href="/assets/colorbox/colorbox.css" />
<link rel="stylesheet" href="/assets/main.css" />
<link rel="stylesheet" href="/assets/moving_boxes_content/css/jquery.jscrollpane.css" />
<link rel="stylesheet" href="/assets/moving_boxes_content/css/style.css" />
<script>
	$('.corner').corner();
	
	$(document).ready(function(){
		$(".iframe").colorbox({iframe:true, width:"800", height:"680",　scrolling:"false"});
		$("#click").click(function(){ 
			$('#click').css({"background-color":"#f00", "color":"#fff", "cursor":"inherit"}).text("Open this window again and this message will still be here.");
			return false;
		});
	});
			
	(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=112651685520077";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
</script>
<div id="fb-root"></div>
<div id="wrapper">
	<div id="header">
		<div id="menu">
			<img width="100px" src="/assets/cart.png">
		</div>
	</div>
	<h1>products</h1>
	<div id="products">
		<% @products.each do |product| %>
		<div class="corner" id="item">
			<%= link_to image_tag('/assets/' + product.product_id + '.gif', {:id => 'product_logo', :border => '0', :alt => product.product_name }), product, {:class => "iframe", } %>
			<%= product.product_id %><br/>
			<%= product.product_name %><br/>
			<%= product.series_name %><br/>
			<%= product.price %>
		</div>
		<% end %>
	</div>
	
	
		<div id="mb_pattern" class="mb_pattern"></div>
		<div id="mb_menu" class="mb_menu">
			<a href="#" data-speed="1000" data-easing="easeOutBack">News</a>
			<a href="#" data-speed="1000" data-easing="easeInExpo">About</a>
			<a href="#" data-speed="1000" data-easing="easeInExpo">Contact</a>
		</div>
		<div id="mb_content_wrapper" class="mb_content_wrapper">
			<span class="mb_close"></span>
			<div class="mb_content">
				<h2>News</h2>
				<div class="mb_content_inner">
					<p>One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin.</p>
					<p>He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections.</p>
					<p>The bedding was hardly able to cover it and seemed ready to slide off any moment.</p>
					<p>His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What's happened to me? " he thought. It wasn't a dream. His room, a proper human</p>
				</div>
			</div>
			<div class="mb_content">
				<h2>About</h2>
				<div class="mb_content_inner">
					<p>She packed her seven versalia, put her initial into the belt and made herself on the way.</p>
					<ul id="mb_imagelist" class="mb_imagelist">
					</ul>
					<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane.</p>
					<p>Pityful a rethoric question ran over her cheek, then she continued her way. On her way she met a copy.</p>
					<p>The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country.</p>
					<p>But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their projects again and again.</p>
				</div>
			</div>
			<div class="mb_content">
				<h2>Contact</h2>
				<div class="mb_content_inner">
					<form>
						<div><label>Name:</label><input type="text" /></div>
						<div><label>Email:</label><input type="text" /></div>
						<div><label>Message:</label><textarea></textarea></div>
						<div><button>Send</button></div>
					</form>
				</div>
			</div>
		</div>



	<div id="footer">
		Copyright &copy; 2012 , LamexJP 
	</div>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<script type="text/javascript" src="/gallery_view/js/jquery-ui.js"></script>
<script type="text/javascript" src="/gallery_view/js/jquery.timers-1.2.js"></script>
<script type="text/javascript" src="/gallery_view/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="/gallery_view/js/jquery.galleryview-3.0-dev.js"></script>
<link rel="stylesheet" type="text/css" href="/gallery_view/css/jquery.galleryview-3.0-dev.css" media="screen" />
<link rel="stylesheet" href="/css/detail.css" />

<script>
$(window).load(function() {
	mCustomScrollbars();
});

function mCustomScrollbars(){
	/* 
	malihu custom scrollbar function parameters: 
	1) scroll type (values: "vertical" or "horizontal")
	2) scroll easing amount (0 for no easing) 
	3) scroll easing type 
	4) extra bottom scrolling space for vertical scroll type only (minimum value: 1)
	5) scrollbar height/width adjustment (values: "auto" or "fixed")
	6) mouse-wheel support (values: "yes" or "no")
	7) scrolling via buttons support (values: "yes" or "no")
	8) buttons scrolling speed (values: 1-20, 1 being the slowest)
	*/
	$("#mcs_container").mCustomScrollbar("vertical",400,"easeOutCirc",1.05,"auto","yes","yes",10); 
}

$(function(){
	$('#myGallery').galleryView({
		panel_width: 400,
		panel_height: 550,
	});
});

(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=112651685520077";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<script src="/jquery_custom_scroller/jquery.mCustomScrollbar.js" type="text/javascript"></script>
<div id="fb-root"></div>
<div id="left" style="float: left; margin-right: 10px;">
	<div id="myGallery">
		<% @product_gallery.each do |product_gallery| %>
			<li><img src="/assets/<%= product_gallery.file_name %>" title="<%= @product.product_name %>" /></li>
		<% end %>
	</div>
</div>

<div id="right" >
	<div style="text-align: center;" id="logo">
		<img src="/assets/<%= @product.product_id %>.gif">
	</div>
	<div id="product_info" style="float:left; margin-right:5px;">
		<p>
		  <b>Products name:</b>
		  <%= @product.product_name %>
		</p>
		<p>
		  <b>Series name:</b>
		  <%= @product.series_name %>
		</p>
		<p>
		  <b>Price:</b>
		  <%= @product.price %>
		</p>
	</div>
	<div style="margin-top:10px; margin-bottom: 10px;"class="fb-like" data-href="http://<%= request.host %>:<%= request.port %>/products/<%= @product.product_id %>" data-send="true" data-layout="box_count" data-width="20" data-show-faces="true"></div>
	<div style="overflow-y: scroll; height:250px;" class="fb-comments" data-href="http://<%= request.host %>:<%= request.port %>/products/<%= @product.product_id %>" data-num-posts="10" data-width="320"></div>
</div>